name: app_frontend_speech_analyzer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^5.0.1
  http: ^0.13.0
  audioplayers: ^0.20.1
  fluttertoast: ^8.2.8
  syncfusion_flutter_charts: ^26.2.14
  fl_chart: ^0.50.1 
  pie_chart: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  # fonts:
  #   - family: NotoSansArabic
  #     fonts:
  #       - asset: fonts/NotoSansArabic-Regular.ttf
